# cd /home/dmitriy/project/k8s/portfolio && kubectl apply -f deployment.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: portfolio
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: portfolio
type: kubernetes.io/tls
data:
  tls.crt: |-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUhXakNDQmtLZ0F3SUJBZ0lNS0ZvMzd1NVFUVzZoN2dGTk1BMEdDU3FHU0liM0RRRUJDd1VBTUZVeEN6QUoKQmdOVkJBWVRBa0pGTVJrd0Z3WURWUVFLRXhCSGJHOWlZV3hUYVdkdUlHNTJMWE5oTVNzd0tRWURWUVFERXlKSApiRzlpWVd4VGFXZHVJRWREUXlCU05pQkJiSEJvWVZOVFRDQkRRU0F5TURJek1CNFhEVEkwTURNd09EQXlORFUwCk9Wb1hEVEkxTURRd09UQXlORFUwT0Zvd0dERVdNQlFHQTFVRUF3d05LaTUzWVhsdlptUjBMbU52YlRDQ0FpSXcKRFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQU5IRzloNVJZb1d3UTIrbTNZaU5lVWh0TjhtZQo4MVl3elYxRUZnZUh3OTlSUGNxWUh4OFpNK210UEIyR1NUVnA3R3R5dnhSa00vVHU5SzFhSCtiKzF4MXIxam9ECjBXTE4rZVY3cTY4eTRHazQwbHgxMm1jcURLZ1BETDN4VEJHY2lSeFZQRkVQekUyTUJZQ0JlTGJMaURUN3AxQVYKa0FtQlVRam5nVkZhK3pDUURnYWV5OURXbWY4OWdYUW9DNWxVZTV6ZkxTc2w5aER1dWJCUlBwN0UxTjVaS2NKKwoyS3lkbzVXWHZHN1BmWExBWllLdGkvUm0wditVaW9PY1dtekd4UVdTNHR3cktnUm1zK0tRc3RvL05GY0xETFAvCjllYzB1UFhEL1BLd2R3MitFSHdnSHp2ZnovWGFpU3hMMGx1R1piOTM0R1N6aFdnWVBITTVvZXdrV2NhbENNT2EKV3JJQ0xXSUpjbUFkdU9EcTdCMEZYTGc4WDI3c25ZbnVzTEFUV3VldEN1TmNBRTExVDhCbVBFVmtjSDE5eVpXLwpsNlprV1JTalBmQ0pCMVJVUDdpcFFYWWtXSCtPbU50MDFVMGg3WW1WclJUUGFrYVNCdkYyNDhqTFh2dnhvZDRTCkhnckxqdE14M0ZzdEIyZnRGeThsYWtTNy9LaEVBTGJjSU9WTTRqVVR4UGRRMzMyd0swNWxyekl3ZldTTjE5UnIKQWpsb2ZRQXhCSnpxcm5BVWwxN1pXaldtSFg5Qnh0Y1loajdDbW10T1dJYXZHaHI1OUxweVowem1ZellKdDM2cAo3enhHV2ZxRXdNSXpXeXhlZjF4V3EyREgrU3M0NW4zSDZlWGtJMDI1dW5xWmV3M29FYVpCTnNYZkhjajhONkFNCmFyZzRwQ0NtaXFZTUh6SXJBZ01CQUFHamdnTmxNSUlEWVRBT0JnTlZIUThCQWY4RUJBTUNCYUF3REFZRFZSMFQKQVFIL0JBSXdBRENCbVFZSUt3WUJCUVVIQVFFRWdZd3dnWWt3U1FZSUt3WUJCUVVITUFLR1BXaDBkSEE2THk5egpaV04xY21VdVoyeHZZbUZzYzJsbmJpNWpiMjB2WTJGalpYSjBMMmR6WjJOamNqWmhiSEJvWVhOemJHTmhNakF5Ck15NWpjblF3UEFZSUt3WUJCUVVITUFHR01HaDBkSEE2THk5dlkzTndMbWRzYjJKaGJITnBaMjR1WTI5dEwyZHoKWjJOamNqWmhiSEJvWVhOemJHTmhNakF5TXpCWEJnTlZIU0FFVURCT01BZ0dCbWVCREFFQ0FUQkNCZ29yQmdFRQpBYUF5Q2dFRE1EUXdNZ1lJS3dZQkJRVUhBZ0VXSm1oMGRIQnpPaTh2ZDNkM0xtZHNiMkpoYkhOcFoyNHVZMjl0CkwzSmxjRzl6YVhSdmNua3ZNRVFHQTFVZEh3UTlNRHN3T2FBM29EV0dNMmgwZEhBNkx5OWpjbXd1WjJ4dlltRnMKYzJsbmJpNWpiMjB2WjNOblkyTnlObUZzY0doaGMzTnNZMkV5TURJekxtTnliREFsQmdOVkhSRUVIakFjZ2cwcQpMbmRoZVc5bVpIUXVZMjl0Z2d0M1lYbHZabVIwTG1OdmJUQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJCkt3WUJCUVVIQXdJd0h3WURWUjBqQkJnd0ZvQVV2UVczODRxVFBIUExlZm9QaFJLaGQ1WVlrWFF3SFFZRFZSME8KQkJZRUZKK1hZbXkzdldDNHd4VFdaQzg0YjlSNDNqN1lNSUlCZmdZS0t3WUJCQUhXZVFJRUFnU0NBVzRFZ2dGcQpBV2dBZGdDaTR3cmtSZSs5clp0K09PMUhaM2RUMTRKYmhKVFhLMTRiTE1TNVVLUkg1d0FBQVk0YjgrRzlBQUFFCkF3QkhNRVVDSUdUT2RFQm1OQmplY2xpQlZIVlplbmZqNW9INXlIMzVuTlYwR3ovRFZrRVhBaUVBcDlPL3VLS04KSXhmR0drakthL0QyUGI0dFVCcm5aR1h6RHpza2lqK3dLSGNBZGdBVFN0OGF0WmhDQ1hnTWIrOU1lcEdrRnJjagpTYzVZVjJyZnJ0cW53cXZnSWdBQUFZNGI4K0tZQUFBRUF3QkhNRVVDSVFEdytRQXQzSHJzMlNUbjdCbmpqa1o2CkJ1bVU0bTM3NmJqcURaSzE0cGk2dWdJZ1psU0Z2bVhDWHU4RzJLU1FkQ25LNFFRRFQwODJkUUJkQ1V4d2RoVkYKUmRrQWRnQk9kYU1uWEpvUXd6aGJiTlRmUDFMckhmRGdqaHVOYWNDeCttU3hZcG81M3dBQUFZNGI4K0xIQUFBRQpBd0JITUVVQ0lHVFRWL3FsVTFTQUtrbGt6SmFJWHFmSzE1MUovK0hrZ3BydGUwRmFPMTE1QWlFQTlCSzYvMlhsCmtVRkwxWXozM1NyMG1CZ2o1K0laTFFucTZBRkowOHNRNVlRd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNWTIKL0wwdjJJd0k4VjNtcVdwaHEyNWg0TDVrYlM3NkhiYVpBd2wyQWZDVlBvSlBRN1ZreTNBYWFlUlFnaHAxM09iWApnVmhrYTdLUlZCY0dycCs0YUNMUGc5cC9NcFk1UHovYjRlK2hQVDEyek9yWWFNQWlhVllLbFZleDU4NnpzSjZtCi9mRml6ckhmaWZhWktaa2ZZdklYMERwVGVWbktIN3VxYVdtZSt5MGhSOUttN2FoTllxcTZaOGIvYzQ3Y2x6YksKRVA3VXZOVkFEc2ZBWWNTTlV1NHk2T0xwbjRlc0U1K1R2WDhNMFA2WldJTnRKME9zQVk3c25IYVhIQzdDL0p4RQplS2Z5ejk3azdkL3Z0T1FGeVZwVnJVdDh5RjJVd3pZOGIrOExrN3JrNEludlJET0RqbDFsZmh2RzlGRlhaUnIyCnF5OGJEUFVqQlVSRHFkdFJJaDg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: |-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS1FJQkFBS0NBZ0VBMGNiMkhsRmloYkJEYjZiZGlJMTVTRzAzeVo3elZqRE5YVVFXQjRmRDMxRTl5cGdmCkh4a3o2YTA4SFlaSk5XbnNhM0svRkdRejlPNzByVm9mNXY3WEhXdldPZ1BSWXMzNTVYdXJyekxnYVRqU1hIWGEKWnlvTXFBOE12ZkZNRVp5SkhGVThVUS9NVFl3RmdJRjR0c3VJTlB1blVCV1FDWUZSQ09lQlVWcjdNSkFPQnA3TAowTmFaL3oyQmRDZ0xtVlI3bk44dEt5WDJFTzY1c0ZFK25zVFUzbGtwd243WXJKMmpsWmU4YnM5OWNzQmxncTJMCjlHYlMvNVNLZzV4YWJNYkZCWkxpM0NzcUJHYXo0cEN5Mmo4MFZ3c01zLy8xNXpTNDljUDg4ckIzRGI0UWZDQWYKTzkvUDlkcUpMRXZTVzRabHYzZmdaTE9GYUJnOGN6bWg3Q1JaeHFVSXc1cGFzZ0l0WWdseVlCMjQ0T3JzSFFWYwp1RHhmYnV5ZGllNndzQk5hNTYwSzQxd0FUWFZQd0dZOFJXUndmWDNKbGIrWHBtUlpGS005OElrSFZGUS91S2xCCmRpUllmNDZZMjNUVlRTSHRpWld0Rk05cVJwSUc4WGJqeU10ZSsvR2gzaEllQ3N1TzB6SGNXeTBIWiswWEx5VnEKUkx2OHFFUUF0dHdnNVV6aU5SUEU5MURmZmJBclRtV3ZNakI5WkkzWDFHc0NPV2g5QURFRW5PcXVjQlNYWHRsYQpOYVlkZjBIRzF4aUdQc0thYTA1WWhxOGFHdm4wdW5KblRPWmpOZ20zZnFudlBFWlorb1RBd2pOYkxGNS9YRmFyCllNZjVLemptZmNmcDVlUWpUYm02ZXBsN0RlZ1Jwa0UyeGQ4ZHlQdzNvQXhxdURpa0lLYUtwZ3dmTWlzQ0F3RUEKQVFLQ0FnQjRnUkY2d3dlVWduZUttTkZqa3RsYjJKbVdjWCtaUUhtSUhRZUdsZC9YMWVSb0Q5QzQzWkpycHI4RQp1dEl0SThiU3hseXJpeEFwb0diZmVna2ZlYjc2d0txVU13TkIvYzZTbStNNHhrSVJUN25Qc1VlZndaRDVyWU9GClRTcUVaMlovNXhxNStoaERaNjcxYmVwNUh4d0VTNWVHTW96R1dRbkMwckgvbVFMNGw1Zm5CNnRQTVNmUGJuYUIKMGtzdmJrK0FBdGdBbEZMdzBTSEwvaSs1cHBvZGpCeW9CSlBWUE16dXJ2Wm90VHA4QTdlTVJNTkR4eGxvQmQwMwowMFpDZkVCTGZtQmhWMDVRcnVxZ3VMeDFFSit4Yk1DRVdnSFpLZmtoL002K1hzNVZENXlLb1Mwd0NOWitoV1lOCkV4VW96R0NBaDQxWWE2T3o4MUF1WktuMmE3OUJpS1NvMEFaNGZoSElvQ2hUbU5ma3JQcldrREJTbUh2Q1I3bUUKZHFZSGkxUjQ4Z0dVdnl5L1Vib1FmM1NZb081RGlJYjlFZEw1RlhjbTJHbmIvOXkrdDZvemFNcjYrMEtldExjZApDMzlkaFJ6WVFqYXBYSmhaV0xsd1BaYVYyU0ljOXhjK2hiTVdMdHVwUVI2OCtNVHAvM1c1am92QWhzVm1yMDFlCkFkMFIvWEdlWFd5MzNXUHhQRWs3aU9KRXVIa0M2ZmlTSmJ4eVpSWjN2R21ZZDg0RDk2RkVYMEFHY0tkNDkwcFMKMjlUMG5qRlgyY012Y0xLaEszMXYvVWxrN2ZhSmJZTDJFSTl4Y2JTNnlOZVZUc2gyZUFIRFhnUFJjTklLMGo3UwpTdVNGT2VqZCs3MXF6UWFGUHd3VkhPdVVaSjFBM21TN0NkWFFNK2d3L3dwQ1dMSFJXUUtDQVFFQS8yMmJmZmZ6ClJxU0tTYTQvTlkvOFB2c2lsUDBPUm1nNFk1ZG04YTZncWFqRlZLZk94bjB3UUcxbDNCc3lFSEF2WEpyT3lnQ1kKalJGNXdJMHR5K2I2S1J1bXUwVHNZenJqMEVQd2RoamJ3aEVaZ2FhUERpemthVUJGRUoxVGxqbERLRVRLOG9FSwp2V1pNaDhjSDZzSWxHSkZWSWFHNmFleHNhaTVqUzBILzZ2UGhrTGpWVUM1M3NWYStJOGFDRUw0azBvcXRWeFJvCnFLQ0FRWTdTRkQxNXd6STV2S3JtbWRxOVBMNnN2V2FydWs3VEFXQUs3eVpHVE1waHVZTG1tS0pCeVRLbm9jZEsKWVJMU0MwY21xeE5oZWQzb01Wd0xkRkpJYXAwczJpTjV1c2g0dU5jYUJaalFCc3Q4VnF5QnQxZC95MndQQlJxZApmNFdWZVZuSURwUEFIUUtDQVFFQTBqOHdzNUdFMEMxd2FPTzNYTjF2MGpWU1RUMGlpamVUcFA1cEcrQnlTaFVjCi9ZckgwZ1Bxb2JWK0VxaS9yWGc3M0FKc1o2VjJ3eG83dFc1OTVibGpxbFF2dUhSQ3VFV0VrdFZSUDkwakg1eXkKNDArTStZYUMybTJFeThzMFpndm15WW40azU0STNKZ1dFLzVYTDVKQW1xRWowN20vOHQwZkx4MGYyMmV6RzBnUgpOK0xsUldTd1pUVkdSQWdwUDJBd1lKbDdZZDNjbVNaWlhCaEhodGdHVWg4QXVuMXREdnM3TFZPb2ZRQ1RxNnd3ClUrbkh5Qkk2UzROY3ZISXI3RmNrcm01L2ZlVVBXaXord0tld3NRVlhWSnlXMGd5ZlFrbkduaWlKVXIvdGZPN2cKTkt5aUxLTVRGeWUyVXFGRXZ1TUUrMnIyYnVzN2x1ZmhDQ25BY0JpNDV3S0NBUUVBMU1zMWpSNHlHQm9mOHY0dApQcXd6a3l5WlJOSUZRSGEyODVGQWUvdmxjVEpmSXdXaDZBNkhVa1ZSWkt0cmEvSnFJcFg5ekovdWR5ZWw3Tm93CjJ2d1VVSWJ1d25qTERtZ1RQb0E3SmNmVDNMdHVLbXJlSndzVFJ2UDZGYnRiMVh6akMvc3pzQS85S0lpL0hTYWMKMitEZUVyZVEyckhub1RNTHB2SDZXc29qTUZQNUNSNVM1N2V1azVrV1VxdWYwOTcwd2tveDJxZndBUHVsbmZnago0Q1RPK2VVdjRKUG9CU2tNR2owbm42cVhTbUU4dkpxTXdXdDdpYUhaQkRtZmJtMU9yUlY4UGZUUGJFdkhuUW1yCmx6NVFLTHpNSWNMeTcvZFV5UzBrSHA4TFhLYUNuRXJuTE42QUFBa3FEdk1zSmRmSmFXa2VvanZvRmtMdG9lbEEKRjVUVHFRS0NBUUJ4clg3OHFJTENPTDlkeHpvK2VQQmNIVDZKeXJOaFBsbVRUWWV4YmZMOXdWcXljQlpJcEp0NQpvZk12elpRT0RFTjVXc29ZWkd2SlkrYkMyNkl3MHNOanRpOHpNWkZkcHlEZWIzNkY1R0I0V0RhVkYwOG5INmFpCnliS1NxaVdEdzQyZWpQNGRlc1paMTlXZ0s5WWlQNWEweE1ubFVickthdXJRZzVQVkFzWGh5MTZiOUE5NUxNNy8KZWdXckJTcWdQTGNMbEJFVlFtdGpWMHZic3JrQjNNM1dHek0rb2xDVVdCeVFEbnE4VTlLRWNRNlVZSVFIMW1zMApweXMrTFJFNHNZbUEwdmdXTHdMVkJCMGVOODBlZWIvVlhQRmpVelhORnF6UW1TUmUzSzFnN3B2RmYwNFVpbnZvCitpem5rcERrRVVXQlZ6MDFqZlRqVEM3dFJmM3Aza1FqQW9JQkFRQ1hTRmhXZW9sQVFySHNsOFZtYXdwRXJ5RnMKZm1rY05HRmh0OENGdGxCYmw0ZUU3VEp3MW13dmg0R2xMUnNjdCt2a2VqMkVNeFY5S3lLRW1ydGpucmUwMWZPMAorWUxUU0ZFTGhRTFNvRFh3KzVIWVdJeE1lNER5S09VY2NjekZab0IvdHRVY1BFUy9OOHc4eEdUemtBZFduL2lECnJHU0ozZ2hIVk5IYUhuenRqTEN2aVZzT1Q0Zit0c05GN2ltc0xwTkNNeXNYRyswTlM0WWk3UERqdGhIeVFRc3IKOTBBa1crM0I2akZOSkREWjJUN1VrZml0MlM4U0huRlY3dVNLamk0eStKUHk3VGQvTVozMjRUQjMra3NpOWxhdwpWbnBNVlV5UlFqcERXUm5XZWhOMHBMYWpMOGIrTkFKK2IzSHVoQ2RxeTUzSzBUYlpwS25ZZTczclJuRFcKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
# Для сертификата
# cat wayofdt.com.crt | base64 | tr -d '\n'

# Для ключа
# cat wayofdt.com.key | base64 | tr -d '\n'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-ru
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-ru
  template:
    metadata:
      labels:
        app: portfolio-ru
    spec:
      containers:
      - name: portfolio-ru
        image: wayofdt/portfolio-ru:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-ru-service
  namespace: portfolio
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: portfolio-ru
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ru-ingress
  namespace: portfolio
  # annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Отключение принудительного перехода на SSL
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - portfolio-ru.wayofdt.com
    secretName: secret-tls
  rules:
  - host: portfolio-ru.wayofdt.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-ru-service
            port:
              number: 80


