name: kidneysmart
description: A new Flutter project.

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # SDK extensions
  # flutter_localizations from sdk depends on meta 1.8.0
  meta: ^1.9.1
  # flutter_localizations from sdk depends on collection 1.16.0
  collection: ^1.17.1
  async: ^2.11.0
  characters: ^1.3.0
  # System
  path_provider: ^2.0.15
  # flutter_localizations from sdk depends on path 1.8.2
  path: ^1.8.3
  platform_info: ^4.0.0
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  connectivity_plus: ^4.0.0

  # Data manipulation
  # di/state
  flutter_riverpod: ^2.3.6
  
  # Internationalization
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  # flutter_test:
  #   sdk: flutter
  # Logging
  logger: ^1.3.0
  shared_preferences: ^2.1.1
  # sqflite_sqlcipher: ^2.1.1+1

  # HTTP
  dio: ^5.1.2
  dio_log:
    git:
         url: https://github.com/flutterplugin/dio_log.git
         ref: dependabot/pub/dio-5.0.3

  # Navigation
  go_router: ^7.0.1

  # Native
  url_launcher: ^6.1.11
  share_plus: ^7.0.0

  # Helper for UI
  flutter_typeahead: ^4.3.8
  lottie: ^2.3.2
  flutter_native_splash: ^2.3.0
  flutter_svg: ^2.0.5
  flex_color_scheme: ^7.1.1
  flutter_markdown: ^0.6.14
  webview_flutter: ^4.2.0
  introduction_screen: ^3.1.8
  google_fonts: ^4.0.4



  # firebase
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_analytics: ^10.4.0




# database
  # sqflite: ^2.2.8+3




  # ******************************
  #  local packages
  # ******************************



dev_dependencies:
  # Analyzer extensions
  dart_code_metrics: ^5.7.3
  very_good_analysis: ^4.0.0+1

  # turn_gen:
    # path: c:/DEV/MY/MY_GITHUB/turn_gen
  turn_gen: ^0.9.2


turn_gen:
  assets_output: "lib/gen/"
  # show_method_comments: true
  folder_barrel: lib\core, 


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/
    - assets/image/
    - assets/icons/
    - assets/db/

  fonts:
    - family: app_icons
      fonts:
        - asset: assets/icons/app_icons.ttf
# flutter pub get && flutter pub run flutter_native_splash:create
# flutter_native_splash:
#   android: true
#   ios: true
#   web: true
#   desktop: true
#   color: "#ffffff"
#   image: assets/image/splash.png

