name: kidneysmart
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state manager

  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0

  # SDK extensions
  meta: ^1.9.1
  collection: ^1.17.2
  async: ^2.11.0
  # System
  path_provider: ^2.1.1
  path: ^1.8.3
  platform_info: ^4.0.2
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  connectivity_plus: ^4.0.2
  # Internationalization
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  # Logging
  logger: ^2.0.2+1

  # local storage
  shared_preferences: ^2.2.2
  # HTTP
  dio: ^5.3.3

  google_fonts: ^6.1.0
  # parser html
  html: ^0.15.4
  # Navigation
  go_router: ^8.2.0
  # Native
  permission_handler: ^11.0.1

  url_launcher: ^6.2.1
  share_plus: ^7.2.1

  webview_flutter: ^4.4.2

  # syncfusion_flutter_pdfviewer: ^23.1.44
  flutter_native_splash: ^2.3.5

  # Helper for UI
  flutter_svg: ^2.0.9
  flex_color_scheme: ^7.3.1
  # TEST
  device_preview: ^1.1.0
  feedback: ^2.6.0

  # firebase
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.4.4
  firebase_analytics: ^10.5.1
  freezed_annotation: ^2.4.1

  # ******************************
  #  local packages
  # ******************************

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  # Code generation
  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  turn_gen: ^2.0.0
  riverpod_generator: ^2.3.5
  custom_lint: ^0.5.6

  # turn_gen:
  # path: c:/DEV/MY/MY_GITHUB/turn_gen
flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/

# dart run turn_gen
turn_gen:
  assets_output: "lib/gen/"
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: false
  remove_alpha_ios: true
  image_path: "assets/image/icon.png"

# flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  web: true
  desktop: false
  color: "#ffffff"
  image: assets/image/logo.png
