name: app_updater
description: App Updater is a Dart package for facilitating app update checks and processing in Dart and Flutter applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: "^3.1.5"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  mockito: ^5.4.4
  retry: ^3.1.2
  # ******************************
  #  local packages
  # ******************************
  dartlog:
    path: ../dartlog
    # git:
      # url: https://github.com/a-dev-mobile/dartlog.git
      # ref: release/1.0.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.9
