# ssh -p 2222 dmitriy@91.223.70.72 "cd /home/dmitriy/project/kidneysmart/k8s/overlays/prod/ && kubectl apply -k ."


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- secret.yaml
- ingress.yaml
- namespace.yaml
- deployment.yaml
