# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: elasticsearch-data-0
#   namespace: kidneysmart-dev
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   resources:
#     requests:
#       storage: 30Gi

---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: elasticsearch-data-1
#   namespace: kidneysmart-dev
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   resources:
#     requests:
#       storage: 30Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: elasticsearch-data-2
#   namespace: kidneysmart-dev
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   resources:
#     requests:
#       storage: 30Gi
