
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    # non_constant_identifier_names: false
    # constant_identifier_names: false


analyzer:
  plugins:
    - custom_lint
  exclude:
    # - "packages/**"
    - "plugin/**"
    # Generated code
    - "**/*.g.dart"
    - "**/*.go"
    - "**/*.freezed.dart"
    - "lib/l10n/**"
    - "lib/**.gen.dart"
    - "lib/generated_plugin_registrant.dart"
    # Tests
    - "test/**.mocks.dart"
    # - "test/*.dart"
    - ".test_coverage.dart"
    # Web
    - "web/**"
    # Build
    - "build/**"
    # Assets
    - "assets/**"
