// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVF2A_-VZghUhJn23VDAs9qlZlzTEOMc',
    appId: '1:989827426867:web:839adf9a5d3cf3b02c5146',
    messagingSenderId: '989827426867',
    projectId: 'kidneysmart-868f2',
    authDomain: 'kidneysmart-868f2.firebaseapp.com',
    databaseURL:
        'https://kidneysmart-868f2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kidneysmart-868f2.appspot.com',
    measurementId: 'G-3MB5D9KE0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDp2eXw4gfdxExveefyTp-L3CXpQAI9pc',
    appId: '1:989827426867:android:36e613d3a430f01e2c5146',
    messagingSenderId: '989827426867',
    projectId: 'kidneysmart-868f2',
    databaseURL:
        'https://kidneysmart-868f2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kidneysmart-868f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfNdVWqmaEkEtkO-EbWAkfVErZpB4SZjg',
    appId: '1:989827426867:ios:517fca22a50406902c5146',
    messagingSenderId: '989827426867',
    projectId: 'kidneysmart-868f2',
    databaseURL:
        'https://kidneysmart-868f2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kidneysmart-868f2.appspot.com',
    iosClientId:
        '989827426867-ag67ovhv4v1cv0h3i2mkp7qd4khu819a.apps.googleusercontent.com',
    iosBundleId: 'com.ckc.kidneysmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfNdVWqmaEkEtkO-EbWAkfVErZpB4SZjg',
    appId: '1:989827426867:ios:db5035d9f06213b22c5146',
    messagingSenderId: '989827426867',
    projectId: 'kidneysmart-868f2',
    databaseURL:
        'https://kidneysmart-868f2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kidneysmart-868f2.appspot.com',
    iosClientId:
        '989827426867-c11d9g1adb3022vv59pb5ubmbaugltif.apps.googleusercontent.com',
    iosBundleId: 'com.ckc.kidneysmart.RunnerTests',
  );
}
