apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-controller-0
  namespace: kidneysmart-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-controller-1
  namespace: kidneysmart-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-controller-2
  namespace: kidneysmart-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
