apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/kafka/kidneysmart-dev-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kafka-node"
              operator: In
              values:
                - "1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/kafka/kidneysmart-dev-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kafka-node"
              operator: In
              values:
                - "1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/kafka/kidneysmart-dev-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kafka-node"
              operator: In
              values:
                - "1"
