// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'api_user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ApiUserInfoImpl _$$ApiUserInfoImplFromJson(Map<String, dynamic> json) =>
    _$ApiUserInfoImpl(
      id: json['id'] as int?,
      token: json['token'] as String?,
      refresh_token: json['refresh_token'] as String?,
      is_phone_confirmed: json['is_phone_confirmed'] as bool? ?? false,
      finance_is_bankruptcy: json['finance_is_bankruptcy'] as bool? ?? false,
      active_moratorium: json['active_moratorium'] as bool? ?? false,
      soft_reject: json['soft_reject'] as bool? ?? false,
      hard_reject: json['hard_reject'] as bool? ?? false,
      in_black_list: json['in_black_list'] as bool? ?? false,
      esia_user: json['esia_user'] as bool? ?? false,
      firstLoan: json['first_loan'] as bool? ?? false,
      short_api: json['short_api'] as bool? ?? false,
      is_esia_user: json['is_esia_user'] as bool?,
      requested_amount: json['requested_amount'] as int?,
      requested_days: json['requested_days'] as int?,
      method_of_disbursement: json['method_of_disbursement'] as int?,
      first_name: json['first_name'] as String? ?? '',
      last_name: json['last_name'] as String? ?? '',
      personal_id: json['personal_id'] as String? ?? '',
      document_number: json['document_number'] as String? ?? '',
      document_series: json['document_series'] as String? ?? '',
      mobile_phone: json['mobile_phone'] as String? ?? '',
      email: json['email'] as String? ?? '',
      date_of_birth: json['date_of_birth'] as String? ?? '',
      document_type: json['document_type'] as String? ?? '',
      issued_by: json['issued_by'] as int?,
      issued_by_string: json['issued_by_string'] as String? ?? '',
      issuer_code: json['issuer_code'] as String? ?? '',
      date_issued: json['date_issued'] as String? ?? '',
      valid_until: json['valid_until'] as String? ?? '',
      birth_place: json['birth_place'] as String? ?? '',
      middle_name: json['middle_name'] as String? ?? '',
      region_registered: json['region_registered'] as String? ?? '',
      district_registered: json['district_registered'] as String? ?? '',
      city_registered: json['city_registered'] as String? ?? '',
      street_type_registered: json['street_type_registered'] as String? ?? '',
      street_registered: json['street_registered'] as String? ?? '',
      house_registered: json['house_registered'] as String? ?? '',
      housing_registered: json['housing_registered'] as String? ?? '',
      building_registered: json['building_registered'] as String? ?? '',
      apartment_registered: json['apartment_registered'] as String? ?? '',
      home_phone_registered: json['home_phone_registered'] as String? ?? '',
      contact_name_registered: json['contact_name_registered'] as String? ?? '',
      contact_type: json['contact_type'] as int?,
      contact_type_id: json['contact_type_id'] == null
          ? null
          : IdLabelValue.fromJson(
              json['contact_type_id'] as Map<String, dynamic>),
      contact_phone_registered:
          json['contact_phone_registered'] as String? ?? '',
      contact_phone: json['contact_phone'] as String? ?? '',
      length_of_stay_registered:
          json['length_of_stay_registered'] as String? ?? '',
      template_address_registered:
          json['template_address_registered'] as String? ?? '',
      region_actual: json['region_actual'] as String? ?? '',
      district_actual: json['district_actual'] as String? ?? '',
      city_actual: json['city_actual'] as String? ?? '',
      street_type_actual: json['street_type_actual'] as String? ?? '',
      street_actual: json['street_actual'] as String? ?? '',
      house_actual: json['house_actual'] as String? ?? '',
      housing_actual: json['housing_actual'] as String? ?? '',
      building_actual: json['building_actual'] as String? ?? '',
      apartment_actual: json['apartment_actual'] as String? ?? '',
      home_phone_actual: json['home_phone_actual'] as String? ?? '',
      length_of_stay_actual: json['length_of_stay_actual'] as String? ?? '',
      template_address_actual: json['template_address_actual'] as String? ?? '',
      education: json['education'] as String? ?? '',
      education_id: json['education_id'] == null
          ? null
          : IdLabelValue.fromJson(json['education_id'] as Map<String, dynamic>),
      monthly_income: json['monthly_income'] as num?,
      monthly_outcome: json['monthly_outcome'] as num?,
      employer: json['employer'] as String? ?? '',
      employer_address: json['employer_address'] as String? ?? '',
      employer_phone: json['employer_phone'] as String? ?? '',
      employer_activity: json['employer_activity'] as int?,
      job_employer_activity: json['job_employer_activity'] == null
          ? null
          : IdLabelValue.fromJson(
              json['job_employer_activity'] as Map<String, dynamic>),
      employer_amount_workers: json['employer_amount_workers'] as int?,
      job_employer_amount_workers: json['job_employer_amount_workers'] == null
          ? null
          : IdLabelValue.fromJson(
              json['job_employer_amount_workers'] as Map<String, dynamic>),
      position: json['position'] as int?,
      job_position: json['job_position'] == null
          ? null
          : IdLabelValue.fromJson(json['job_position'] as Map<String, dynamic>),
      position_type: json['position_type'] as int?,
      job_position_type: json['job_position_type'] == null
          ? null
          : IdLabelValue.fromJson(
              json['job_position_type'] as Map<String, dynamic>),
      work_phone: json['work_phone'] as String? ?? '',
      internal_phone: json['internal_phone'] as String? ?? '',
      next_salary_date: json['next_salary_date'] as String? ?? '',
      work_experience_last: json['work_experience_last'] as String? ?? '',
      work_experience_total: json['work_experience_total'] as String? ?? '',
      real_estate: json['real_estate'] as String? ?? '',
      marital_status: json['marital_status'] as int?,
      marital_status_id: json['marital_status_id'] == null
          ? null
          : IdLabelValue.fromJson(
              json['marital_status_id'] as Map<String, dynamic>),
      number_of_children: json['number_of_children'] as int?,
      number_of_children_id: json['number_of_children_id'] == null
          ? null
          : IdLabelValue.fromJson(
              json['number_of_children_id'] as Map<String, dynamic>),
      loans_before: json['loans_before'] as String? ?? '',
      loans_before_amount: json['loans_before_amount'] as String? ?? '',
      loans_before_bank_name: json['loans_before_bank_name'] as String? ?? '',
      monthly_expenses_on_loans:
          json['monthly_expenses_on_loans'] as String? ?? '',
      loans_current_bank_name: json['loans_current_bank_name'] as String? ?? '',
      credit_card_limit: json['credit_card_limit'] as String? ?? '',
      requested_product: json['requested_product'] as String? ?? '',
      employment_type: json['employment_type'] as String? ?? '',
      gender: json['gender'] as String? ?? '',
      car_type: json['car_type'] as String? ?? '',
      car_year: json['car_year'] as String? ?? '',
      car_number: json['car_number'] as String? ?? '',
      car_amount: json['car_amount'] as int?,
      village_registered: json['village_registered'] as String? ?? '',
      village_actual: json['village_actual'] as String? ?? '',
      additional_income_source:
          json['additional_income_source'] as String? ?? '',
      family_income: json['family_income'] as int? ?? 0,
      contact_name: json['contact_name'] as String? ?? '',
      contact_last_name: json['contact_last_name'] as String? ?? '',
      target_url: json['target_url'] as String? ?? '',
      password: json['password'] as String? ?? '',
      new_password: json['new_password'] as String? ?? '',
      code: json['code'] as String? ?? '',
      lang: json['lang'] as String? ?? '',
      postal_code_registered: json['postal_code_registered'] as String? ?? '',
      postal_code_actual: json['postal_code_actual'] as String? ?? '',
      finance_liabilities: json['finance_liabilities'] as int?,
      finance_repayment_monthly_sum:
          json['finance_repayment_monthly_sum'] as int?,
      finance_amount_unpaid_loans: json['finance_amount_unpaid_loans'] as int?,
      finance_type_user_history: json['finance_type_user_history'] as int?,
      finance_max_loan_sum: json['finance_max_loan_sum'] as int?,
      finance_last_loan_sum: json['finance_last_loan_sum'] as int?,
      university_name: json['university_name'] as String? ?? '',
      faculty: json['faculty'] as String? ?? '',
      academic_degree: json['academic_degree'] as String? ?? '',
      academic_start_year: json['academic_start_year'] as String? ?? '',
      disability_group: json['disability_group'] as String? ?? '',
      activity_type: json['activity_type'] as String? ?? '',
      agis_project: json['agis_project'] as String? ?? '',
      step: json['step'] as String? ?? '',
      ga_cid: json['ga_cid'] as String? ?? '',
      smartphone: json['smartphone'] as String? ?? '',
      motorbike: json['motorbike'] as String? ?? '',
      bank_account_transit_account:
          json['bank_account_transit_account'] as String? ?? '',
      bank_account_bank_name: json['bank_account_bank_name'] as String? ?? '',
      bank_account_bank_bic: json['bank_account_bank_bic'] as String? ?? '',
      bank_account_bank_tax_number:
          json['bank_account_bank_tax_number'] as String? ?? '',
      bank_account_number: json['bank_account_number'] as String? ?? '',
      moratorium_end_date: json['moratorium_end_date'] as String? ?? '',
      partner_url: json['partner_url'] as String? ?? '',
      okato_registered: json['okato_registered'] as String? ?? '',
      okato_actual: json['okato_actual'] as String? ?? '',
      fias_id_registered: json['fias_id_registered'] as String? ?? '',
      fias_id_actual: json['fias_id_actual'] as String? ?? '',
      terminalRepayment: json['terminal_repayment'] as String?,
      pushNotificationAgree: json['push_notification_agree'] as bool?,
      confirmationMethod: json['confirmation_method'] as String?,
      allowedAccessToPersonalAccount:
          json['allowed_access_to_personal_account'] as bool?,
      isStandardQuestionnaireFirst:
          json['is_standard_questionnaire_first'] as bool? ?? false,
      isStandardQuestionnaireRepeated:
          json['is_standard_questionnaire_repeated'] as bool? ?? false,
      isStandardPersonalAccountFirst:
          json['is_standard_personal_account_first'] as bool? ?? false,
      isStandardPersonalAccountRepeated:
          json['is_standard_personal_account_repeated'] as bool? ?? false,
    );

Map<String, dynamic> _$$ApiUserInfoImplToJson(_$ApiUserInfoImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'token': instance.token,
      'refresh_token': instance.refresh_token,
      'is_phone_confirmed': instance.is_phone_confirmed,
      'finance_is_bankruptcy': instance.finance_is_bankruptcy,
      'active_moratorium': instance.active_moratorium,
      'soft_reject': instance.soft_reject,
      'hard_reject': instance.hard_reject,
      'in_black_list': instance.in_black_list,
      'esia_user': instance.esia_user,
      'first_loan': instance.firstLoan,
      'short_api': instance.short_api,
      'is_esia_user': instance.is_esia_user,
      'requested_amount': instance.requested_amount,
      'requested_days': instance.requested_days,
      'method_of_disbursement': instance.method_of_disbursement,
      'first_name': instance.first_name,
      'last_name': instance.last_name,
      'personal_id': instance.personal_id,
      'document_number': instance.document_number,
      'document_series': instance.document_series,
      'mobile_phone': instance.mobile_phone,
      'email': instance.email,
      'date_of_birth': instance.date_of_birth,
      'document_type': instance.document_type,
      'issued_by': instance.issued_by,
      'issued_by_string': instance.issued_by_string,
      'issuer_code': instance.issuer_code,
      'date_issued': instance.date_issued,
      'valid_until': instance.valid_until,
      'birth_place': instance.birth_place,
      'middle_name': instance.middle_name,
      'region_registered': instance.region_registered,
      'district_registered': instance.district_registered,
      'city_registered': instance.city_registered,
      'street_type_registered': instance.street_type_registered,
      'street_registered': instance.street_registered,
      'house_registered': instance.house_registered,
      'housing_registered': instance.housing_registered,
      'building_registered': instance.building_registered,
      'apartment_registered': instance.apartment_registered,
      'home_phone_registered': instance.home_phone_registered,
      'contact_name_registered': instance.contact_name_registered,
      'contact_type': instance.contact_type,
      'contact_type_id': instance.contact_type_id,
      'contact_phone_registered': instance.contact_phone_registered,
      'contact_phone': instance.contact_phone,
      'length_of_stay_registered': instance.length_of_stay_registered,
      'template_address_registered': instance.template_address_registered,
      'region_actual': instance.region_actual,
      'district_actual': instance.district_actual,
      'city_actual': instance.city_actual,
      'street_type_actual': instance.street_type_actual,
      'street_actual': instance.street_actual,
      'house_actual': instance.house_actual,
      'housing_actual': instance.housing_actual,
      'building_actual': instance.building_actual,
      'apartment_actual': instance.apartment_actual,
      'home_phone_actual': instance.home_phone_actual,
      'length_of_stay_actual': instance.length_of_stay_actual,
      'template_address_actual': instance.template_address_actual,
      'education': instance.education,
      'education_id': instance.education_id,
      'monthly_income': instance.monthly_income,
      'monthly_outcome': instance.monthly_outcome,
      'employer': instance.employer,
      'employer_address': instance.employer_address,
      'employer_phone': instance.employer_phone,
      'employer_activity': instance.employer_activity,
      'job_employer_activity': instance.job_employer_activity,
      'employer_amount_workers': instance.employer_amount_workers,
      'job_employer_amount_workers': instance.job_employer_amount_workers,
      'position': instance.position,
      'job_position': instance.job_position,
      'position_type': instance.position_type,
      'job_position_type': instance.job_position_type,
      'work_phone': instance.work_phone,
      'internal_phone': instance.internal_phone,
      'next_salary_date': instance.next_salary_date,
      'work_experience_last': instance.work_experience_last,
      'work_experience_total': instance.work_experience_total,
      'real_estate': instance.real_estate,
      'marital_status': instance.marital_status,
      'marital_status_id': instance.marital_status_id,
      'number_of_children': instance.number_of_children,
      'number_of_children_id': instance.number_of_children_id,
      'loans_before': instance.loans_before,
      'loans_before_amount': instance.loans_before_amount,
      'loans_before_bank_name': instance.loans_before_bank_name,
      'monthly_expenses_on_loans': instance.monthly_expenses_on_loans,
      'loans_current_bank_name': instance.loans_current_bank_name,
      'credit_card_limit': instance.credit_card_limit,
      'requested_product': instance.requested_product,
      'employment_type': instance.employment_type,
      'gender': instance.gender,
      'car_type': instance.car_type,
      'car_year': instance.car_year,
      'car_number': instance.car_number,
      'car_amount': instance.car_amount,
      'village_registered': instance.village_registered,
      'village_actual': instance.village_actual,
      'additional_income_source': instance.additional_income_source,
      'family_income': instance.family_income,
      'contact_name': instance.contact_name,
      'contact_last_name': instance.contact_last_name,
      'target_url': instance.target_url,
      'password': instance.password,
      'new_password': instance.new_password,
      'code': instance.code,
      'lang': instance.lang,
      'postal_code_registered': instance.postal_code_registered,
      'postal_code_actual': instance.postal_code_actual,
      'finance_liabilities': instance.finance_liabilities,
      'finance_repayment_monthly_sum': instance.finance_repayment_monthly_sum,
      'finance_amount_unpaid_loans': instance.finance_amount_unpaid_loans,
      'finance_type_user_history': instance.finance_type_user_history,
      'finance_max_loan_sum': instance.finance_max_loan_sum,
      'finance_last_loan_sum': instance.finance_last_loan_sum,
      'university_name': instance.university_name,
      'faculty': instance.faculty,
      'academic_degree': instance.academic_degree,
      'academic_start_year': instance.academic_start_year,
      'disability_group': instance.disability_group,
      'activity_type': instance.activity_type,
      'agis_project': instance.agis_project,
      'step': instance.step,
      'ga_cid': instance.ga_cid,
      'smartphone': instance.smartphone,
      'motorbike': instance.motorbike,
      'bank_account_transit_account': instance.bank_account_transit_account,
      'bank_account_bank_name': instance.bank_account_bank_name,
      'bank_account_bank_bic': instance.bank_account_bank_bic,
      'bank_account_bank_tax_number': instance.bank_account_bank_tax_number,
      'bank_account_number': instance.bank_account_number,
      'moratorium_end_date': instance.moratorium_end_date,
      'partner_url': instance.partner_url,
      'okato_registered': instance.okato_registered,
      'okato_actual': instance.okato_actual,
      'fias_id_registered': instance.fias_id_registered,
      'fias_id_actual': instance.fias_id_actual,
      'terminal_repayment': instance.terminalRepayment,
      'push_notification_agree': instance.pushNotificationAgree,
      'confirmation_method': instance.confirmationMethod,
      'allowed_access_to_personal_account':
          instance.allowedAccessToPersonalAccount,
      'is_standard_questionnaire_first': instance.isStandardQuestionnaireFirst,
      'is_standard_questionnaire_repeated':
          instance.isStandardQuestionnaireRepeated,
      'is_standard_personal_account_first':
          instance.isStandardPersonalAccountFirst,
      'is_standard_personal_account_repeated':
          instance.isStandardPersonalAccountRepeated,
    };

_$IdLabelValueImpl _$$IdLabelValueImplFromJson(Map<String, dynamic> json) =>
    _$IdLabelValueImpl(
      id: json['id'] as int?,
      label: json['label'] as String?,
      value: json['value'] as String?,
    );

Map<String, dynamic> _$$IdLabelValueImplToJson(_$IdLabelValueImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'label': instance.label,
      'value': instance.value,
    };
