name: Build and Push Docker images on changes

on:
  push:
    paths:
      - 'backend/api-log/**'
      - 'backend/api-auth/**'
      - 'backend/api-gateway/**'

jobs:
  build_and_push_api_logs:
    if: contains(github.event.head_commit.modified, './backend/api-log/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend/api-log
          file: ./backend/api-log/Dockerfile
          push: true
          tags: wayofdt/kidneysmart-api-log:latest

  build_and_push_api_auth:
    if: contains(github.event.head_commit.modified, 'backend/api-auth/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend/api-auth
          file: ./backend/api-auth/Dockerfile
          push: true
          tags: wayofdt/kidneysmart-api-auth:latest

  build_and_push_api_gateway:
    if: contains(github.event.head_commit.modified, 'backend/api-gateway/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend/api-gateway
          file: ./backend/api-gateway/Dockerfile
          push: true
          tags: wayofdt/kidneysmart-api-gateway:latest
