name: Build and Push Docker images on changes

on:
  push:
    paths:
      - 'backend/api-log/**'
      - 'backend/api-auth/**'
      - 'backend/api-gateway/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: api-log
          - name: api-auth
          - name: api-gateway

    steps:
      - uses: actions/checkout@v4
      
      - name: Check changed files in ${{ matrix.service.name }}
        id: files
        run: |
          echo "Checking for modified files in backend/${{ matrix.service.name }}/"
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
              CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- "backend/${{ matrix.service.name }}/")
          else
              CHANGED_FILES=$(git show --name-only -- "backend/${{ matrix.service.name }}/")
          fi
          if [ -n "$CHANGED_FILES" ]; then
            echo "Modified files:"
            echo "$CHANGED_FILES"
            echo "::set-output name=trigger::true"
          else
            echo "No changes detected in backend/${{ matrix.service.name }}/"
            echo "::set-output name=trigger::false"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push if changes in ${{ matrix.service.name }}
        if: steps.files.outputs.trigger == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./backend/${{ matrix.service.name }}
          file: ./backend/${{ matrix.service.name }}/Dockerfile
          push: true
          tags: wayofdt/kidneysmart-${{ matrix.service.name }}:latest
