name: Build and Push Docker images on changes

on:
  push:
    paths:
      - 'backend/api-log/**'
      - 'backend/api-auth/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: api-log
            version: v0.0.2
          - name: api-auth
            version: v0.0.1
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/${{ matrix.service.name }}
          file: ./backend/${{ matrix.service.name }}/Dockerfile
          push: true
          tags: wayofdt/kidneysmart-${{ matrix.service.name }}:${{ matrix.service.version }}
