name: Flutter CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > kidneysmart.jks

      - name: Set Environment Variables
        run: |
          echo "KEYSTORE_PATH=$(realpath kidneysmart.jks)" >> $GITHUB_ENV

      - name: Log Environment Variables
        run: |
          echo "Keystore file path: $KEYSTORE_PATH"

      - name: Build APK
        run: flutter build apk --release
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}

      - name: Find APK File
        run: |
          apk_path=$(find ./build/app/outputs/apk/release -name '*.apk' | head -n 1)
          echo "APK_PATH=$apk_path" >> $GITHUB_ENV

      - name: Calculate APK Checksum
        run: |
          apk_checksum=$(sha256sum ${{ env.APK_PATH }} | awk '{ print $1 }')
          echo "APK_CHECKSUM=$apk_checksum" >> $GITHUB_ENV

      - name: Send APK and Checksum
        run: |
          echo "APK Path: ${{ env.APK_PATH }}"
          ls -l ${{ env.APK_PATH }}
          response=$(curl --request POST \
                          --url ${{ secrets.API_ENDPOINT }} \
                          --header 'Content-Type: multipart/form-data' \
                          --form "file=@${{ env.APK_PATH }}" \
                          --form "checksum=${{ env.APK_CHECKSUM }}")
          echo "Server response: $response"
