// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC29Y5rN6drnaZ1SRa1MqbsbJb9Vz6PkJw',
    appId: '1:501294960046:web:ba5d93f2e64e29564f4c3f',
    messagingSenderId: '501294960046',
    projectId: 'kidneysmart-a0453',
    authDomain: 'kidneysmart-a0453.firebaseapp.com',
    storageBucket: 'kidneysmart-a0453.appspot.com',
    measurementId: 'G-PZL9SKZC8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZlZW--ih7UMWIPci92tDTBNa17r2JGHY',
    appId: '1:501294960046:android:bd6f45a9b27bbb614f4c3f',
    messagingSenderId: '501294960046',
    projectId: 'kidneysmart-a0453',
    storageBucket: 'kidneysmart-a0453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7P6QEsH1GhJJzwokK-geLvQlWL92-2yo',
    appId: '1:501294960046:ios:0703d65aadf69f434f4c3f',
    messagingSenderId: '501294960046',
    projectId: 'kidneysmart-a0453',
    storageBucket: 'kidneysmart-a0453.appspot.com',
    iosBundleId: 'com.wayofdt.kidneysmart',
  );
}
